### ISSUE TITLE
freeAction.tpa parse error

### ISSUE THREAD

**Issue by Raseven** [The-Gate-Project/klatu-tweaks-and-fixes#6]
I get the following when trying to install the Free Action component:

[klatu/lib/freeAction.tpa] PARSE ERROR at line 119 column 64-69
Near Text: opcode
        GLR parse error

[klatu/lib/freeAction.tpa]  ERROR at line 119 column 64-69
Near Text: opcode
        Parsing.Parse_error
ERROR: parsing [klatu/lib/freeAction.tpa]: Parsing.Parse_error
Stopping installation because of error.

**Comment by GraionDilach** [comment]
Likely fixed already with merging #5, because I can't repro this one.

Will close next week unless it can be reproduced after that one.

**Comment by Raseven** [comment]
The master branch .zip I downloaded a couple of hours ago did not have those changes. I downloaded the .zip again and it contains those changes and installed. Bizarre.

**Comment by Raseven** [comment]
the missing ORs fixed it, I downloaded again and it installed
