### ISSUE TITLE
Line 361 in freeAction.tpa?

### ISSUE THREAD

**Issue by MikeX1234** [The-Gate-Project/klatu-tweaks-and-fixes#9]
Shoudn't it be READ_ASCII (off + **0x28**) c7__c7__resource ?

**Comment by Raseven** [comment]
Is this an issue only with line 361 or all of the "READ_ASCII (off + 0x14) c7__c7__resource" lines?

**Comment by MikeX1234** [comment]
As far as I've looked into this, line 361 should be the only wrong one.
The similar other ones are fine.

**Comment by 11jo** [comment]
I have modified the error, but this mod is beyond my knowledge to maintain, so don't hesitate to send a pull request if you encounter other issues.

**Comment by MikeX1234** [comment]
Thanks
